export { createCompass } from "./create.js"
export { defaultSources, docsSource, packageSource, cliSource, repoSource, testsSource, configSource } from "./sources/index.js"
export { mapBehaviorsFromFindings, summarizeBehaviorMap } from "./behavior.js"
export { computeScore, scoreToRecommendation, scoreToLabel, explainScore } from "./score.js"
export { collectBearings, collectTerrain, formatBearingsForPrompt, formatTerrainForPrompt } from "./evidence/collect.js"
export { stageProposal, stageOutcome } from "./propose.js"
export * from "./types.js"
